### ISSUE TITLE
Inserir links dos desafios resolvidos

### ISSUE THREAD

**Issue by mayronceccon** [training-center/php-study-group#14]
Seria interessante nós adicionarmos os links dos desafios resolvidos dentro das pastas.

Assim não ficaria somente em vídeo a resolução.

```
Fulano:
 - https://github.com
Ciclano: 
- https://github.com
```

**Comment by Diego-Brocanelli** [comment]
Excelente ideia @mayronceccon  voi adicionar!

**Comment by Diego-Brocanelli** [comment]
Sugestões inserida nas PR :)
