### ISSUE TITLE
Gerar conteúdo de estudo para o RoadMap

### ISSUE THREAD

**Issue by Diego-Brocanelli** [training-center/php-study-group#22]
Olá, pessoal.

Como vamos  conduzir a criação de conteúdo para o RoadMap que criamos?

Temos diversos tópicos para guiar os estudos, porém acredito que podemos criar conteúdos para cada tópico e assim estudarmos e documentar cada estudo.
 
## 1º - Qual a melhor plataforma para produção de conteúdo?

- ***Minhas sugestões:***
    - Blog posts.
        - Podemos escrever no Medium do Training Center.
    - Vídeo tutoriais.
        - Podemos hospedar no canal do YouTube do Training Center.

## 2º - Como podemos organizar a produção desse material?

- ***Minha Sugestão:***
    - Planilha no Google Drive.
        - Assim podemos inserir e acompanhar o desenvolvimento de cada material a ser produzido.
    - Trello
        - Uma forma simples e organizada de gerenciar a produção de conteúdo.

**Comment by Diego-Brocanelli** [comment]
Uma ferramenta bacana para a pergunta 2 é o Trello.

**Comment by lucassantos61** [comment]
Para a pergunta 1 gostei da sugestão acho que será acessível a todos, e sobre a pergunta 2 além do google drive a gente poderia usar o google keep, pois ele permite colocar um colaborador em uma tarefa talvez isso seja útil ma hora de produzir algum material.

**Comment by Diego-Brocanelli** [comment]
@lucassantos61 boa, podemos analisar, pois acredito que é mais comum ter uma conta do Google do que a do Trello.

**Comment by amadeu01** [comment]
Tem uns caras que fazem conteúdo para Android chamados Mindorks. As vezes, eles não tem o curso de alguma coisa, mas tem um repositorio de exemplo de uma arquitetura 'X' com os posts no blog deles em ordem de 'construir um raciocínio' para você entender o que eles fizeram naquele repositório. Então, acho uma forma legal é tipo ter um link entre os posts, como se fosse uma continuidade de algo. Ou, deixar o post de uma forma como se alguém conseguisse aproveitar aquilo para falar de algo além. Tipo, construir historias dentro dos posts. Acho que é uma forma legal de fazer com que o leitor retorne para o blog por curiosidade e daí, você consegue manter as pessoas conectadas. 😄

**Comment by mayronceccon** [comment]
Posts são mais práticos de fazer do que um vídeo, minha opinião!
O Trello se não for o pago não há o limite de 5 por projeto?

**Comment by Diego-Brocanelli** [comment]
@mayronceccon Não faço ideia disso no Trello, preciso ver.

O vídeo seria mais uma opção, caso a pessoa queira produzir material nesse formato.

Pois podemos manter posts e vídeo, ou até mesmo mais formatos como por exemplo podcast.

A ideia mesmo é fecharmos para produzir conteúdo :)

**Comment by amadeu01** [comment]
@mayronceccon acho que se for um trello publico não tem limite. Mas, não tenho certeza. Pois já vi uns trelos tipo do Gitlab ou Mozilla que tem uma galera e acho que eles não pagam.

Public
A public board is visible to anyone with the link to the board and will show up in search engines like Google. Only those users added as members to the board can edit.

Setting a board to public allows all members of Trello to view your board and optionally vote or comment. You can turn other features (like comments and voting) on and off for public members via the 'Settings' menu.

Note: Boards within teams that subscribe to  Business Class will see additional privileges for the team's admins, such as the ability to see and edit all boards in a team.

Acho que como board público, qualquer pessoa pode ir lá e comentar. 😄

**Comment by dyhalmeida** [comment]
Fala pessoal, sou mais um novato no grupo.
Então, existe uma iniciativa aqui no GitHub chamada [VaiNaWeb](https://github.com/VaiNaWeb/primeiros-passos-na-web) que tem como objetivo ajudar no desenvolvimento de página responsivas, acessíveis e semântica. Eles utilizam como ferramenta para passar o conteúdo para seu público o [GitBook](https://www.gitbook.com/), [Slides](https://slides.com/) e resumos em arquivo .MD.

Vejam um material deles sobre o assunto **Construindo Formulários**
- [GitBook - Formulários](https://vainaweb.gitbooks.io/primeiros-passos-web/construindo-formularios.html)
- [Slides - Formulários](http://slides.com/vainaweb/primeiros-passos-na-web-05#/)

Eu gostei muito desse modelo, principalmente do Gitbook e os Slides.
Talvez ótimas ferramentas para utilizarmos também.

Em relação a organização, o Trello funciona melhor. Séria ótimo adotá-lo.

**Comment by Diego-Brocanelli** [comment]
Temos que pensar com carinho na adoção de novas ferramentas, pois cada nova ferramenta é um trabalho a mais, pois deve ser mantida e monitorada. Por isso minha sugestão inicial de utilizarmos o Medium e YouTube do Training Center, pois são plataformas já utilizadas pela comunidade.

Não estou falando que não devemos adotar novas plataformas, apenas expondo os pontos que devemos analisar antes de adotar.

As sugestões do @dyhalmeida  são excelentes, devemos analisar.

**Comment by lucassantos61** [comment]
Eu concordo com o @Diego-Brocanelli  , sou a favor de ferramentas simples e fáceis de se manter e de se usar por que terermos pessoas de diversos níveis juntas. E também há o trabalho para manter tudo isso.

**Comment by Diego-Brocanelli** [comment]
Fora o trabalho de manter, temos que ter consciência que devemos auxiliar possíveis pessoas que tenham vontade de produzi conteúdo, porém com pouca ou nenhuma experiência, esse é um dos pilares do grupo de estudos.

Para focarmos nossa discussão, vamos fechar no Medium e no Youtube para iniciarmos esse projeto de criação de conteúdo, conforme evoluímos vamos analisando o ferramental.

**Comment by dyhalmeida** [comment]
Show, Medium e Youtube, tá ótimo!

**Comment by Diego-Brocanelli** [comment]
Pessoal, fechado então:

- ***Plataformas escolhidas:***
     - Medium.
     - YouTube. 

Vamos criar a documentação dentro do repositório.
