### ISSUE TITLE
Criação de projeto de nível intermediário

### ISSUE THREAD

**Issue by Diego-Brocanelli** [training-center/php-study-group#27]
Olá, pessoal.

Como finalizamos o processo de criação de um projeto prático para o nível iniciante, podemos desenvolver um projeto de nível intermediário para que seja desenvolvido em conjunto com o RoadMap do mesmo nível.

Com isso busco sugestões para projetos.

Por favor, quem puder contribuir seria fantástico.

Para simplificar podemos sugerir da seguinte forma, sendo:

### Exemplo de preenchimento

***Nome do Projeto:*** Projeto Exemplo
***Descrição do projeto***
Breve descrição da ideia do projeto...

**Comment by lucasmarques73** [comment]
**Nome do Projeto** To-do PHP
**Descrição do projeto**
Algo semelhante ao to-do list, com um formulário para pessoa preencher uma tarefa à fazer. Uma lista com as tarefas à serem feitas e botões para marcá-las como concluídas ou não.
Pode ser feito usando orientação a objetos, conexão com o banco. área de login com usso de sessão.
E podemos ver de posteriormente fazer ele usando um MVC do zero, mas já seria mais avançado.

**Comment by mayronceccon** [comment]
Minha opinião é que devemos ter um projeto onde iniciamos no nível intermediário e possamos evoluir com o nível avançado, usando o mesmo projeto.

Acho muito válida a ideia do @lucasmarques73 do To-do.

**Comment by lucasmarques73** [comment]
Podemos montar um novo projeto iniciante.. Semelhante ao to-do.. mas sem banco de dados e session.. Utilizando um arquivo texto para salvar as informações.. Desta forma não precisa ser introduzido ao iniciante banco de dados.. mas sim trabalhar com arquivos(Não sei se isso seria pra iniciante.). Pois sem salvar as tarefas em algum lugar fica complicado..

**Comment by mayronceccon** [comment]
Não acho necessário montar um novo projeto iniciante, a parte do iniciante se seguido o roadmap não tem OO, com isso acabaria criando um trabalho muito grande para migrar de estruturado para OO na parte intermediária. 

Projetos intermediários e avançados deveriam ter essa possibilidade de evolução.

Essa é a minha visão.

**Comment by Diego-Brocanelli** [comment]
Galera, vamos fechar então com a sugestão do @lucasmarques73  para implementar a ideia do Todo List.

Quem poderia auxiliar na produção do material? Como por exemplo:

- Mockups.
- Descrição e detalhamento do projeto.
- Material de apoio.

**Comment by WendellAdriel** [comment]
Não estou a participar ativamente de nenhum grupo de estudos, mas como estou desde o início do Training Center como mentor e atualmente não atuo mais como mentor, posso ajudar na descrição e detalhamento e materiais de apoio caso queiram :wink:

**Comment by Diego-Brocanelli** [comment]
@WendellAdriel toda ajuda é sempre muito bem vinda!

**Comment by renesoaresse** [comment]
E ai pessoal, tudo certinho com todos?
Tava lendo aqui o RoadMap e que tal criarmos uma aplicação para simular as provas de certificação?
Nisso poderíamos introduzir todos os itens do roadmap do intermediário e seria escalável para o avançado. Caso o pessoal queira, posso descrever melhor a ideia.

**Comment by dyhalmeida** [comment]
Amei a ideia de @renesoaresse , aprovo!

**Comment by Diego-Brocanelli** [comment]
Pessoal, vamos fechar inicialmente em 02 projetos sendo eles:

- ***To Do List***
- ***Guia de perguntas para a certificação***

Agora temos que selecionar que irá elaborar as documentações para os respectivos projetos.

**Comment by Diego-Brocanelli** [comment]
A definição dos membros responsáveis pela elaboração dos projetos para o nível intermediário, será realizado na reunião mensal do grupo de estudos a ser realizado nesta data 31/01/2018 das 21h00min às 22h00min.

Com isso essa issue será encerrada.
