### ISSUE TITLE
Definição da pauta para 5º - Reunião do Grupo de Estudos

### ISSUE THREAD

**Issue by Diego-Brocanelli** [training-center/php-study-group#28]
Olá, pessoal.

Para nossa próxima reunião que ocorrerá dia 30/01/2018 das 21:00 às 22:00 temos que definir os tópicos da pauta. 

Com isso peço que deixem nos comentários sugestões para inclusão no documento.

**Comment by lucasmarques73** [comment]
Definir sobre o projeto intermediário.
Definir sobre criação de conteúdo para o grupo no medium e youtube.

**Comment by osmar-vil** [comment]
Concordo com o @lucasmarques73 sobre definir projeto pra intermediário e a criação de conteúdo

**Comment by mayronceccon** [comment]
Um ponto é definirmos como iniciar um projeto. Muita gente não tem ideia de como fazer isso. Temos a trilha de estudo, mas não como iniciar um projeto com essa trilha.

**Comment by lucasmarques73** [comment]
Já que bastante gente fez o exercício iniciante.. Podemos ter um code review...

**Comment by Diego-Brocanelli** [comment]
@lucasmarques73 sua sugestão de realizar code review é para o hangout da próxima reunião? Ou via GitHub?

**Comment by dyhalmeida** [comment]
Acho que o principal assunto dessa reunião, deveria ser sobre a criação de conteúdo para o youtube e medium. Por exemplo, poderíamos seguir o roadmap para a criação de conteúdos de forma organizada para que um membro não duplique um conteúdo já produzido por outro membro. Ou abrir issues seguindo o cronograma do roadmap e cada membro pegar um conteúdo para criar, incentivando a todos a gerar conteúdo.

**Comment by Diego-Brocanelli** [comment]
Na minha visão, a próxima reunião deveria ser para alinhar esses pontos de criação de conteúdo. Pois serão os pontos base para todo um ciclo de atividades.

Uma sugestão, podemos usar a aba ***Projects*** para gerenciarmos toda a criação de conteúdo, centralizando tudo no GitHub, facilitando o acesso a todos.

O processo de definição do projeto intermediário poderia correr em paralelo ou caso os membros desejem, realizar uma outra reunião específica para o ponto em si. Pois com isso podemos levantar material a ser discutido.

**Comment by lucasmarques73** [comment]
Podemos fazer talvez um outro vídeo.. pode consumir muito tempo os reviews.. Mas seria interessante pra gente comparar como cada um fez o projeto e o pq utilizou cada coisa.

**Comment by Diego-Brocanelli** [comment]
Justamente @lucasmarques73 tenho a mesma visão, o review é parte importante do processo de aprendizado. Vamos agendar uma data para realizar este processo.

**Comment by Diego-Brocanelli** [comment]
Pessoal, com base nos apontamentos listados por todos aqui na issue irei encerrar e criar a pauta para a reunião. 

Obrigado pela colaboração de todos.
