### ISSUE TITLE
Primeiro Livro

### ISSUE THREAD

**Issue by thurrio** [training-center/php-study-group#3]
<p> Gostaria de saber qual será o nosso primeiro livro, que tal abrirmos uma enquete para votação? </p>
<p> Podemos fazer citações e depois a votação </p>

**Comment by manzoliric** [comment]
Ainda não foi definido nada, mas tem muitas indicações desse livro.
https://novatec.com.br/livros/php-orientacao-objetos-3ed/

**Comment by Diego-Brocanelli** [comment]
@arthurrio Estamos definindo data, horário e plataforma para que possamos marcar uma reunião (online) e definirmos o start dos estudos, inicialmente a galera está empolgada em criar um projeto prático e com base nele gerar os estudos.

**Comment by thurrio** [comment]
Massa!

**Comment by Diego-Brocanelli** [comment]
@arthurrio realizamos a primeira reunião do grupo d estudos convido de de uma olhada na pauta e gravação da reunião. 

https://github.com/richmanzoli/Grupo-de-Estudos-PHP-POO/blob/master/reunioes/pautas/1_reuniao_27_09_2017.md

com isso, podemos fechar essa issue?
