### ISSUE TITLE
Coding Dojo - Preparando para Certificação Zend

### ISSUE THREAD

**Issue by lucasmarques73** [training-center/php-study-group#36]
# Ideia
Estou me preparando para realizar a prova e tirar a certificação [Zend](http://www.zend.com/en/services/certification/php-certification) e temos alguns simulados para estar resolvendo como preparação.
A ideia é nos reunirmos regularmente e assim realizar algumas questões tentando entender o porquê de cada resposta. Algo próximo a essa [playlist](https://www.youtube.com/playlist?list=PLt3tq0MBSMpkDwdzAdeMt7qLXLZyPkwbU)

# Como vai ser feito cada reunião
Podemos nos reunir uma vez por semana ou mais caso todos tenham interesse e disponibilidade, eu poderia estar comandando as reuniões  e a cada reunião uma pessoa seja nosso Host assim diversificando e permitindo que todos consigam participar ativamente das reuniões.  
O Host vai compartilhar sua tela e abrir um dos sites com simulados para todos verem quais questões vamos resolver. O Host resolve a questão e diz o porquê escolheu tal resposta, mesmo que seja, por que eu estou chutando, e antes de revelar a resposta, os outros participantes vão dar seu palpite e explicar o motivo, caso seja necessário, o participante compartilha sua tela e explica o motivo por chegar a tal conclusão. Após isso vemos quem acertou e partimos para a próxima questão.

# Pós Reunião
Após a reunião podemos colocar no repositório as questões que resolvemos e os motivos escolhidos para ficar como base de consulta para outras pessoas que queiram estudar também.

---
Espero feedback de todos e vamos rumo a certificação!!

**Comment by Diego-Brocanelli** [comment]
Olá, @lucasmarques73 

Excelente iniciativa, sua sugestão de ***Pós Reunião***  para documentar, deve ser feita sim! 

Pois as reuniões irão gerar muito conhecimento bacana e esse material irá enriquecer nosso repositório do grupo de estudos.

**Comment by lucassantos61** [comment]
Curtí , muito sua ideía @lucasmarques73  , acho que seria bacana dividir a reunião por quantidade de questões ou topícos, para que o host e os demais participantes tenham uma noção do que estudar e assim ficar situado dos assuntos da reunião , pois  independente se ele participar daa primeira ou da sexta ele vai ver o tema e vai poder se situar.

**Comment by renesoaresse** [comment]
@lucasmarques73 eu curti muito a ideia. Como o @lucassantos61 acredito que essa abordagem seja a mais indicada, indico seguir os tópicos propostos no [link](http://www.zend.com/en/services/certification/php-certification) e pegar algumas questões de provas passadas.

**Comment by WendellAdriel** [comment]
Quando tirei a minha certificação (em 2015) escrevi um artigo sobre a minha preparação para a mesma, se ainda ajudar em algo, podem acessar **[aqui](https://github.com/CodeShareEducation/old-articles/blob/master/2015-11-25-preparando-para-a-certificacao-php.md)**

**Comment by lucasmarques73** [comment]
Podemos ir marcando.. 3 questões por reunião e ir subindo de acordo com o andamento da reunião. Uma ideia é seguir esse [simulado](http://www.zendexam.com/), ele tem várias questões separadas por tópicos, infelizmente são questões do exame 200-550 sobre o PHP 5.5 mas muita coisa ainda é igual.
Excelente post @WendellAdriel

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Que pé anda a iniciativa?

**Comment by lucasmarques73** [comment]
Criei uma forms para coletarmos os nomes e horário que pode participar dos interessados.  
Favor, respondam pra gente dar continuidade no projeto
https://goo.gl/forms/dPSUq4A4oTmICuzf1

**Comment by Diego-Brocanelli** [comment]
@lucasmarques73 mencione o for em nosso Slack para que o grupo possa preencher os dados.

**Comment by lucassantos61** [comment]
@lucasmarques73  no form não seria bacana colocar um caixa de seleção para os dias da semana ? Acho que vai facilitar a visualização dos dados

**Comment by lucasmarques73** [comment]
@lucassantos61 dei uma melhorada nele lá.

**Comment by lucassantos61** [comment]
Agora ficou show de bola

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Que pé estamos com a issue?

**Comment by nelsonmfinda** [comment]
Olá @lucasmarques73  gostaria de participar do grupo de estudo, como faço?

**Comment by Diego-Brocanelli** [comment]
Olá, @dev-nelsonjr 
Sou o líder do grupo de esrudos, para entrar no grupo é simples, basta acessar nosso channel no slack. `php-studies` fazer uma breve apresentação e pronto :)

Qualquer dúvida estou a disposição.

**Comment by Diego-Brocanelli** [comment]
Boa tarde, pessoal.

Criei uma estrutura para estudos para a certificação, com isso abri um PR https://github.com/training-center/php-study-group/pull/40

**Comment by Diego-Brocanelli** [comment]
Bom dia, pessoal.
 A PR #40 foi finalizada, podendo assim já ser utilizada para estudos da certificação.

**Comment by lucasmarques73** [comment]
Dado as informações levantadas no PR #40 , vamos seguir pela estrutura definida lá.
Sendo assim vamos fechar esta issue.
