### ISSUE TITLE
Trello Dojo

### ISSUE THREAD

**Issue by irwing-max** [training-center/php-study-group#39]
Minha idea é criar um quadro do **Trello** pra incluir dos os tipos de desafios. No quadro, teria colunas de **ToDo List** separado por níveis. Após a conclusão da tarefa, o card seria passado para outra coluna somente para code review. Não sei seria possível ou se ficaria bagunça devido a quantidade de pessoas que estão inclusas no canal. Mas o propósito é manter a galera ativa, treinando, evoluindo.

**Comment by Diego-Brocanelli** [comment]
Olá, @irwing-max .

Sua ideia é interessante, e se ao invés de Trello utilizássemos o GitHub projects?

Pois assim, toda a documentação permaneceria junto ao repositório.

**Comment by irwing-max** [comment]
Oi @Diego-Brocanelli eu não conheço essa ferramenta. Mas se ela for mais viável para atingir o propósito da ideia. Ótimo!

**Comment by Diego-Brocanelli** [comment]
@irwing-max  de uma olha e  vê o que acha, https://github.com/training-center/php-study-group/projects

Acredito que atenda as necessidades.

**Comment by Diego-Brocanelli** [comment]
Pessoal, vamos seguir com essa trhead ou podemos encerrar?

**Comment by Diego-Brocanelli** [comment]
@irwing-max  qual o andamento da issue? Vamos seguir com ela aberta?

**Comment by irwingmax** [comment]
Como foi criado um plano de estudos para o rumo a certificação. Não vejo necessidade de prosseguir com essa issue. Pode fechar.
